//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace client_desktop.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Text.RegularExpressions;

    public partial class Admin : User, IDataErrorInfo
    {
        public string Error
        {
            get { throw new NotImplementedException(); }
        }

        public string this[string columnName]
        {
            get
            {
                Regex specialchars = new Regex("[^a-zA-Z¹êœæ³]");

                string result = null;
                if (columnName == "FirstName")
                {
                    if (string.IsNullOrEmpty(FirstName))
                        result = "Please enter a First Name";
                    else if (specialchars.IsMatch(FirstName))
                        result = "Forbidden Characters";
                }
                if (columnName == "SecondName")
                {
                    if (string.IsNullOrEmpty(SecondName))
                        result = "Please enter a Second Name";
                    else if (specialchars.IsMatch(SecondName))
                        result = "Forbidden Characters";
                }

                return result;
            }
        }
    }
}
